-- Project Tracker: import through phpMyAdmin's SQL tab
CREATE DATABASE IF NOT EXISTS project_tracker CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE project_tracker;
CREATE TABLE IF NOT EXISTS projects (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(160) NOT NULL,
 repository VARCHAR(255) NOT NULL DEFAULT '',
 public_url VARCHAR(500) NOT NULL DEFAULT '',
 description TEXT NOT NULL,
 next_step TEXT NOT NULL,
 started_on DATE NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
